#!/bin/bash

#skryp ktory robi bla bla bla bla
#pierwsza zmienna to sciezka do pliku
#druga zmienna to rozmiar pliku

if [ $# -lt 2 ]
then
echo "Podales za niewlasciwa ilosc parametrow"
else
echo "Uruchomiono skrypt kopiujacy zdjecia do archiwum"

mkdir tymczasowe_archiwum
cd tymczasowe_archiwum

cp $1/*jpeg .
cp $1/*JPEG .
cp $1/*png .
cp $1/*PNG .

for i in *.PNG;
    do "$i" "$(basename "$file" .PNG).png"
    done

for j in *.JPEG;
    do "$j" "$(basename "$file" .JPEG).jpeg"
    done

find *.png -name "* *" | while read;
    do
    mv "$REPLY" "${REPLY// /_}"
    done

find *.jpeg -name "* *" | while read;
    do
    mv "$REPLY" "${REPLY// /_}"
    done

convert -resize $2 *.png
convert -resize $2 *.jpeg

tar -cf archiwum.tar *.jpeg *.png
fi