#!/bin/bash

#skryp ktory robi bla bla bla bla
#pierwsza zmienna to sciezka do pliku
#druga zmienna to rozmiar pliku

if [ $# -lt 2 ]
then
echo "Podales za niewlasciwa ilosc parametrow"
else
echo "Uruchomiono skrypt kopiujacy zdjecia do archiwum"

mkdir tymczasowe_archiwum

cp ./$1/*.jpeg ./tymczasowe_archiwum
cp ./$1/*.JPEG ./tymczasowe_archiwum
cp ./$1/*.png ./tymczasowe_archiwum
cp ./$1/*.PNG ./tymczasowe_archiwum

cd tymczasowe_archiwum

for file in *.PNG
do
    mv "$file" "${file%.PNG}.png"
done

for file in *.JPEG
do
    mv "$file" "${file%.JPEG}.jpeg"
done

find ./*.png -name "* *" | while read;
do
    mv "$REPLY" "${REPLY// /_}"
done

find ./*.jpeg -name "* *" | while read;
do
    mv "$REPLY" "${REPLY// /_}"
done

for file in *.jpeg
do
    convert -resize $2 $file $file
done

for file in *.png
do
    convert -resize $2 $file $file
done

cd ..
tar -cf archiwum.tar ./$1/*.jpeg ./$1/*.png

fi